---
- name: remove apache2 server
  apt: name=apache2 state=absent
  sudo: true

- name: install nginx
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - nginx

- name: remove default nginx config
  file: path=/etc/nginx/sites-enabled/default state=absent
  sudo: true
  tags: nginx
  notify: restart nginx

- name: copy nginx config files
  template: src={{ item.src }} dest=/etc/nginx/sites-available/{{ item.dest }}
  sudo: true
  tags: nginx
  with_items: vhosts
  notify: restart nginx

- name: enable platform virtual host
  file: src=/etc/nginx/sites-available/{{ item.dest }} dest=/etc/nginx/sites-enabled/{{ item.dest }} state=link
  sudo: true
  tags: nginx
  with_items: vhosts
  notify: restart nginx

# @todo ufw playbook?
- name: open ports in firewall
  ufw: rule=allow proto=tcp port={{ item }}
  sudo: true
  with_items:
    - 80
    - 443
  tags: ufw
  notify: reload firewall
  when: firewall_disabled is not defined or not firewall_disabled
