---
- name: Check required variables are defined
  fail: msg="{{ item }} is not defined"
  when: "{{ item }} is not defined"
  with_items: [ 'vhost_id', 'vhost_names', 'vhost_docroot', 'vhost_app_config' ]

- include: ssl_{{ ssl_certs_flavor }}.yml
  when: https_enabled

- include: vhost_write.yml
