---
# Actions for provided certificate files
- block:
  - name: ensure {{ ssl_server_home }} exists
    file: path={{ ssl_server_home }} state=directory owner=root group=www-data mode=0750
  
  - name: set up targets
    set_fact:
      _server_key_file: "{{ ssl_server_home }}/ansible_nginx_{{ vhost_id }}.key"
      _server_cert_file: "{{ ssl_server_home }}/ansible_nginx_{{ vhost_id }}.crt"

  - name: copy the certificate
    copy: src={{ ssl_certfiles_cert_file }} dest={{ _server_cert_file }} mode=640 owner=root group=www-data

  - name: copy the key
    copy: src={{ ssl_certfiles_key_file }} dest=/tmp/{{ vhost_id }}.key mode=700 owner=root group=root

  # following two are either / or
  - name: decrypt ssl key if password set
    command: openssl rsa -in /tmp/{{ vhost_id }}.key -out {{ _server_key_file }} -passin pass:{{ ssl_certfiles_key_password }}
    args:
      creates: "{{ _server_key_file }}"
    when: ssl_certfiles_key_password is defined and ssl_certfiles_key_password
  # ... or ...
  - name: copy the key to its definitive location
    copy: src=/tmp/{{ vhost_id }}.key dest={{ _server_key_file }} mode=640 group=www-data remote_src=yes
    when: ssl_certfiles_key_password is not defined and not ssl_certfiles_key_password

  when: ssl_certs_flavor == 'certfiles'
  become: True
  become_user: root
